// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw3BJx17k32W4xZgbs3gJshCei15mzkok',
    appId: '1:898545781047:web:c92f0e8ef5501899f8b2b2',
    messagingSenderId: '898545781047',
    projectId: 'notifications-484d0',
    authDomain: 'notifications-484d0.firebaseapp.com',
    databaseURL: 'https://notifications-484d0-default-rtdb.firebaseio.com',
    storageBucket: 'notifications-484d0.appspot.com',
    measurementId: 'G-0RYK6EMLEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbg5pvRwnQS7S8O0FYhAkbohBtBhptiT8',
    appId: '1:898545781047:android:fa75f6610a641cb7f8b2b2',
    messagingSenderId: '898545781047',
    projectId: 'notifications-484d0',
    databaseURL: 'https://notifications-484d0-default-rtdb.firebaseio.com',
    storageBucket: 'notifications-484d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPcml7BVjiNos4nlpCEMjNTRZRKkDGPI',
    appId: '1:898545781047:ios:9d958913f5480f97f8b2b2',
    messagingSenderId: '898545781047',
    projectId: 'notifications-484d0',
    databaseURL: 'https://notifications-484d0-default-rtdb.firebaseio.com',
    storageBucket: 'notifications-484d0.appspot.com',
    androidClientId: '898545781047-681qt5o355lkqv7v566k7s034jmif0fn.apps.googleusercontent.com',
    iosClientId: '898545781047-gletmoppvog7elepim5ri9nbgvo26cgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHPcml7BVjiNos4nlpCEMjNTRZRKkDGPI',
    appId: '1:898545781047:ios:9d958913f5480f97f8b2b2',
    messagingSenderId: '898545781047',
    projectId: 'notifications-484d0',
    databaseURL: 'https://notifications-484d0-default-rtdb.firebaseio.com',
    storageBucket: 'notifications-484d0.appspot.com',
    androidClientId: '898545781047-681qt5o355lkqv7v566k7s034jmif0fn.apps.googleusercontent.com',
    iosClientId: '898545781047-gletmoppvog7elepim5ri9nbgvo26cgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw3BJx17k32W4xZgbs3gJshCei15mzkok',
    appId: '1:898545781047:web:9b8eda2b665d34b0f8b2b2',
    messagingSenderId: '898545781047',
    projectId: 'notifications-484d0',
    authDomain: 'notifications-484d0.firebaseapp.com',
    databaseURL: 'https://notifications-484d0-default-rtdb.firebaseio.com',
    storageBucket: 'notifications-484d0.appspot.com',
    measurementId: 'G-N05SB9G4HZ',
  );
}
